Allow exp instruction for xfb output of copyshader
GPUOpen-Drivers/llpc pull request #1083
Opened 2020-12-09 00:31 UTC by xuechen417

In current PathInOutImportExport pass, "exp" instruction will not be
generated in copyshader for generic outputs if transform feedback is
enabled. This restriction is enforced to fix a dxvk issue in early year.
The fragment shader is allowed its input receiving xfb output of the
copyshader. To fix it, we will immediadely generate "exp" instruction
for generic output in `patchCopyShaderGenericOutputExport` if xfb is
enabled.

2020-12-09 00:56 UTC, amdvlk-admin commented
### Test summary for commit fd3b38d8b90f4b6329fac85642d3581a45ca98f5
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev eb28c7ef53329f838e693f233696823330e964c0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ae9a45d0cf074c06dad804b42927178d7c5f3849</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144498)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26320/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21853/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26319/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21854/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 24851/48152 (51.6%)</li>
<li>Failed: 0/48152 (0.0%)</li>
<li>Skipped: 23301/48152 (48.4%)</li>
</ul></details>


</ul></details>

2020-12-09 07:21 UTC, xuechen417 commented
V1: Move the change to `addExportInstForGenericOutput`. if xfb is enabled, generate "exp" instruciton immediately ; otherwise perform `recordVertexAttribExport`.

2020-12-09 07:51 UTC, amdvlk-admin commented
### Test summary for commit b3b57cab92335ae0a461940bd67a54dc92ceecbb
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev eb28c7ef53329f838e693f233696823330e964c0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ae9a45d0cf074c06dad804b42927178d7c5f3849</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144498)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26320/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21853/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26319/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21854/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 24851/48152 (51.6%)</li>
<li>Failed: 0/48152 (0.0%)</li>
<li>Skipped: 23301/48152 (48.4%)</li>
</ul></details>


</ul></details>

2020-12-09 08:34 UTC, JaxLinAMD commented
retest this please

2020-12-09 09:00 UTC, amdvlk-admin commented
### Test summary for commit b3b57cab92335ae0a461940bd67a54dc92ceecbb
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev eb28c7ef53329f838e693f233696823330e964c0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 63761ecfd2d3cfa61a756ce0a72e1ca1cdae333a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ae9a45d0cf074c06dad804b42927178d7c5f3849</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144498)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26320/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21853/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26319/48173 (54.6%)</li>
<li>Failed: 0/48173 (0.0%)</li>
<li>Skipped: 21854/48173 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 24851/48152 (51.6%)</li>
<li>Failed: 0/48152 (0.0%)</li>
<li>Skipped: 23301/48152 (48.4%)</li>
</ul></details>


</ul></details>

2020-12-10 05:29 UTC, xuechen417 commented
V2: Revert all changes. Just remove the check of `enableXfb` in `visitReturnInst`.

2020-12-10 05:45 UTC, kuhar commented on lgc/patch/PatchInOutImportExport.cpp
> +    SmallVector<Value *, 8> attribExport(8, undef);
nit: use the default SmallVector size: https://llvm.org/docs/ProgrammersManual.html#llvm-adt-smallvector-h

2020-12-10 08:05 UTC, xuechen417 commented
Thanks @kuhar for your review and suggestion. My last push V2 missed to remove that piece of code. V3 is the expected change.

2020-12-10 08:42 UTC, amdrexu approved these changes

2020-12-10 09:20 UTC, amdvlk-admin commented
### Test summary for commit c01c99fd3cce083d30d7d5b402537b1b6c6950e1
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev eb28c7ef53329f838e693f233696823330e964c0</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 0acf0c3687e7601248a8332c7e7b88af0e88c7cd</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev ae9a45d0cf074c06dad804b42927178d7c5f3849</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/144513)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26320/48178 (54.6%)</li>
<li>Failed: 0/48178 (0.0%)</li>
<li>Skipped: 21858/48178 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26319/48178 (54.6%)</li>
<li>Failed: 0/48178 (0.0%)</li>
<li>Skipped: 21859/48178 (45.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 24851/48157 (51.6%)</li>
<li>Failed: 0/48157 (0.0%)</li>
<li>Skipped: 23306/48157 (48.4%)</li>
</ul></details>


</ul></details>

2020-12-11 04:47 UTC, xuechen417 commented
The change needs to re-work if export to multiple streams.

2020-12-11 05:24 UTC, amdrexu requested changes
We encounter some special cases that need to handle.

2020-12-15 07:26 UTC, xuechen417 commented
Close this PR . The issue is resovled in PR #1099 .

2020-12-15 07:26 UTC, closed without merging