Change pointer arithmetic to use getelementptr.
GPUOpen-Drivers/llpc pull request #1091
Opened 2020-12-10 15:45 UTC by rdomingu

Change inttoptr(add x, const) -> gep(inttoptr x, const) to improve
value tracking and load/store vectorization. Fix regression with
non-array indexing.

2020-12-10 15:47 UTC, rdomingu commented
This is pull request is a follow-up to https://github.com/GPUOpen-Drivers/llpc/pull/1028 which was reverted due to a regression when indexing a non-array structure.

2020-12-15 02:46 UTC, JaxLinAMD commented
@rdomingu  please rebase

2020-12-15 16:58 UTC, kuhar requested changes

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +// is associated with.
I'd reword it like this:
```
the former is associated with whatever x AND const point to; the latter is associated ONLY with whatever x points to
```

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +// We can assume in LLPC that const is not associated with any object (which makes this transformation valid) but that's
I'd reword this like this:
```
In LLPC/LGC, we can assume that const does not point to any object (which makes this transformation valid) but that's 
```

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  // Change inttoptr ( add x, const ) -> gep ( inttoptr x, const )
nit: missing comma at the end

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  BinaryOperator *const binaryOperator = dyn_cast<BinaryOperator>(intToPtr.getOperand(0));
nit: use auto, the type is clear from the right hand side

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  const ConstantInt *const constOffset = dyn_cast<ConstantInt>(binaryOperator->getOperand(1));
nit: use auto, the type is clear from the right hand side

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  const DataLayout dataLayout = intToPtr.getModule()->getDataLayout();
missing reference?

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  IntToPtrInst *const newIntToPtr = new IntToPtrInst(binaryOperator->getOperand(0), intToPtr.getType());
nit: use auto, the type is clear from the right hand side

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  GetElementPtrInst *const getElementPtr =
nit: use auto, the type is clear from the right hand side

2020-12-15 16:58 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +// We can assume in LLPC that const is not associated with any object (which makes this transformation valid) but that's
Can you also paste the link to the llvm-dev discussion from the other PR?

2020-12-17 16:35 UTC, rdomingu commented on lgc/patch/PatchPeepholeOpt.cpp
> +  // Change inttoptr ( add x, const ) -> gep ( inttoptr x, const )
Where?

2020-12-17 16:37 UTC, rdomingu commented on lgc/patch/PatchPeepholeOpt.cpp
> +  const DataLayout dataLayout = intToPtr.getModule()->getDataLayout();
Where?

2020-12-17 16:50 UTC, rdomingu commented on lgc/patch/PatchPeepholeOpt.cpp
> +  const DataLayout dataLayout = intToPtr.getModule()->getDataLayout();
Nevermind. I got it.

2020-12-17 16:53 UTC, rdomingu commented on lgc/patch/PatchPeepholeOpt.cpp
> +  // Change inttoptr ( add x, const ) -> gep ( inttoptr x, const )
You mean missing _period_ at the end?

2020-12-17 19:14 UTC, kuhar commented on lgc/patch/PatchPeepholeOpt.cpp
> +  // Change inttoptr ( add x, const ) -> gep ( inttoptr x, const )
ah, yes

2020-12-18 02:19 UTC, amdvlk-admin commented
### Test summary for commit 1294ed0f61226916b9ed4ac40ca2a86d2970981c
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 8abed125acda77ccf700ddd0f5bf0114d25ac135</li>
<li>SPVGEN: dev e1f1881d84cd1c7a6c1d661cbac0e619b4e110c1</li>
<li>XGL: dev 2f28502c5e6e4f059a014ab30001a191328f7a5d</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 0472e039337a255a85b0f6f4ac927aa19261c2f0</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/192520)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26332/48178 (54.7%)</li>
<li>Failed: 0/48178 (0.0%)</li>
<li>Skipped: 21846/48178 (45.3%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26331/48178 (54.7%)</li>
<li>Failed: 0/48178 (0.0%)</li>
<li>Skipped: 21847/48178 (45.3%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 24863/48157 (51.6%)</li>
<li>Failed: 0/48157 (0.0%)</li>
<li>Skipped: 23294/48157 (48.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 26230/48007 (54.6%)</li>
<li>Failed: 0/48007 (0.0%)</li>
<li>Skipped: 21777/48007 (45.4%)</li>
</ul></details>


</ul></details>

2020-12-18 06:49 UTC, kuhar approved these changes
Thanks for the fixes

2020-12-22 03:21 UTC, amdrexu approved these changes
@rdomingu Please help to click the button "Close Conversation" once you fix a review issue pointed by review comments in the future. This could help the one who made the comments to quickly check your update as a reminder. Thanks very much.

2020-12-25 05:46 UTC, JaxLinAMD commented
@rdomingu  ping

2020-12-28 02:12 UTC, rdomingu commented
> @rdomingu Please help to click the button "Close Conversation" once you fix a review issue pointed by review comments in the future. This could help the one who made the comments to quickly check your update as a reminder. Thanks very much.

Will do. Thank you.

2020-12-28 02:13 UTC, rdomingu commented
> @rdomingu ping

I am not sure what this ping is for.

2020-12-28 02:47 UTC, JaxLinAMD commented
> > @rdomingu ping
> 
> I am not sure what this ping is for.

the same thing "Close conversion" :)

2020-12-29 04:19 UTC, merged