Expose spvgen build path to XGL
GPUOpen-Drivers/llpc pull request #1132
Opened 2021-01-18 18:58 UTC by kuhar

This propagates the spvgen build location to the XGL scope so that we can use it in XGL's tests that use amdllpc.

2021-01-19 08:24 UTC, JaxLinAMD commented
retest this please

2021-01-19 09:08 UTC, amdvlk-admin commented
### Test summary for commit acb8b09aec4e9a35da084b593c0456e732e7c25f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev 1e61f9ab6eb2041c73d7e7bd8f2021fa05a4bdd8</li>
<li>SPVGEN: dev 7c1cf34dd7eb4d3a6e6652c26292eef1bfcbcaf0</li>
<li>XGL: dev 19df23b69b3e7117d0fb738eb2badb91846220a7</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 1d0178f3d37675e22bf1a16267d1d070fcb8d720</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/224697)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 26847/56155 (47.8%)</li>
<li>Failed: 0/56155 (0.0%)</li>
<li>Skipped: 29308/56155 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 26847/56155 (47.8%)</li>
<li>Failed: 0/56155 (0.0%)</li>
<li>Skipped: 29308/56155 (52.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 25436/56232 (45.2%)</li>
<li>Failed: 0/56232 (0.0%)</li>
<li>Skipped: 30796/56232 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 26862/56155 (47.8%)</li>
<li>Failed: 0/56155 (0.0%)</li>
<li>Skipped: 29293/56155 (52.2%)</li>
</ul></details>


</ul></details>

2021-01-19 10:44 UTC, dstutt approved these changes
LGTM

2021-01-20 09:14 UTC, Flakebi requested changes

2021-01-20 09:14 UTC, Flakebi commented on llpc/CMakeLists.txt
> +    set(XGL_SPVGEN_BUILD_PATH ${CMAKE_CURRENT_BINARY_DIR}/spvgen PARENT_SCOPE)
Sorry for the late comment, I didn’t notice this earlier. I think you need to use `${CMAKE_BINARY_DIR}/spvgen` here (note: no CMAKE_**CURRENT**_BINARY_DIR, which refers to compiler/llpc/spvgen).

Looks good to me other than that.

2021-01-20 15:36 UTC, kuhar commented
V1: Use the correct binary dir variable.

2021-01-20 15:37 UTC, kuhar commented
Thanks, @Flakebi. Both variables pointed to the same directory, so I didn't realize I used the other one.

2021-01-20 15:55 UTC, Flakebi approved these changes

2021-01-21 06:48 UTC, merged