Add useSubgroupSize check to the ShaderModuleUsage
GPUOpen-Drivers/llpc pull request #1188
Opened 2021-03-12 10:13 UTC by jiaolu

1) Add shader subgroup related feature check in the Pipelinecontext
2) shaderMode useSubgroupSize can get from ShaderModuleUsage

2021-03-12 10:36 UTC, amdrexu reviewed
LGTM

2021-03-15 08:12 UTC, JaxLinAMD commented
retest this please

2021-03-15 08:45 UTC, amdvlk-admin commented
### Test summary for commit 31a0bdeca4d3f85932decdb7a991f73f257143c8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev a8cf07c212059bae9d018c05fc896e1115a2f077</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev d3cc9bf1baae76359c2ebab6e7122e6b9c428455</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 570c8bd44f15e3a0ff7547c0804a08549c7fbb3f</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/238988)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31351/59723 (52.5%)</li>
<li><details><summary>Failed: 1/59723 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 28371/59723 (47.5%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31352/59723 (52.5%)</li>
<li>Failed: 0/59723 (0.0%)</li>
<li>Skipped: 28371/59723 (47.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31515/59819 (52.7%)</li>
<li><details><summary>Failed: 1/59819 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_delayed_destroy
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 28303/59819 (47.3%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34994/59723 (58.6%)</li>
<li>Failed: 0/59723 (0.0%)</li>
<li>Skipped: 24729/59723 (41.4%)</li>
</ul></details>


</ul></details>

2021-03-15 13:23 UTC, kuhar requested changes

2021-03-15 13:23 UTC, kuhar commented on llpc/context/llpcComputeContext.h
> +  virtual bool useSubgroupSize() const;
nit: `usesSubgroupSize`? `use` makes this function sound like it makes it use it instead of checking if it already does it

2021-03-15 13:23 UTC, kuhar commented on llpc/context/llpcGraphicsContext.cpp
> +  for (uint32_t i = 0; i < shaderInfos.size(); ++i) {
Use a range based for loop

2021-03-15 13:23 UTC, kuhar commented on llpc/context/llpcGraphicsContext.cpp
> +    const ShaderModuleData *moduleData = reinterpret_cast<const ShaderModuleData *>(shaderInfos[i]->pModuleData);
nit: you can use `auto* moduleData = ...`. The return type is obvious because it's on the right hand side.

2021-03-15 13:23 UTC, kuhar commented on llpc/util/llpcShaderModuleHelper.cpp
> +      if ((strncmp(reinterpret_cast<const char *>(&codePos[1]), "SPV_AMD_shader_ballot",
Use llvm::StringRef to perform the string comparison

2021-03-16 08:49 UTC, amdvlk-admin commented
### Test summary for commit c3da0a588e50d135a60a8c2945bf5f993e389f31
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>PAL: dev a8cf07c212059bae9d018c05fc896e1115a2f077</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>XGL: dev d3cc9bf1baae76359c2ebab6e7122e6b9c428455</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 20799acf951a8e0b79d95154ecfca851a2f63b98</li>
</ul></details>

<details><summary>CTS tests (Failed: 3/238988)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 31351/59723 (52.5%)</li>
<li><details><summary>Failed: 1/59723 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 28371/59723 (47.5%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 31351/59723 (52.5%)</li>
<li><details><summary>Failed: 1/59723 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_delayed_destroy
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 28371/59723 (47.5%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 31515/59819 (52.7%)</li>
<li><details><summary>Failed: 1/59819 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Fail
```
</p></details></li>

<li>Skipped: 28303/59819 (47.3%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34994/59723 (58.6%)</li>
<li>Failed: 0/59723 (0.0%)</li>
<li>Skipped: 24729/59723 (41.4%)</li>
</ul></details>


</ul></details>

2021-03-16 09:18 UTC, merged