Add interface for trace ray library manager
GPUOpen-Drivers/llpc pull request #2054
Opened 2022-09-27 09:01 UTC by LLJJDD

Add helper interface ITraceRayLibMgr, driver will inherit and implement it, and compiler will use it to obtain a trace ray library index.

This is the preparation for the upcoming change to implement trace ray specialization functionality.

Background:
In indirect mode, when trace ray specialization is chosen, compiler will not build trace ray library along with pipeline shaders. Instead, a trace ray library table will be built by driver, and compiler will query the index to it by providing necessary trace ray parameters. Driver will compile specialized trace ray libraies based on the given paramters and cache them, so that they can be shared between different RT pipelines. This will prvent compiling and uploading a same library for multiple times.

2022-09-27 10:28 UTC, amdvlk-admin commented
### Test summary for commit daa54b3d2f52fcd9f632a1393f89824232f28d58
<details><summary>CTS tests (Failed: 2/286530)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 36222/72652 (49.9%)</li>
<li>Failed: 0/72652 (0.0%)</li>
<li>Not Supported: 36430/72652 (50.1%)</li><li>Warnings: 0/72652 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 40417/72699 (55.6%)</li>
<li><details><summary>Failed: 2/72699 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_tracing_pipeline.data_spill.execute_callable.uint16
Stack trace: Flake

FAILURE: dEQP-VK.subgroups.clustered.framebuffer.subgroupclusteredmul_i8vec2_tess_control
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 32280/72699 (44.4%)</li><li>Warnings: 0/72699 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 37135/72706 (51.1%)</li>
<li>Failed: 0/72706 (0.0%)</li>
<li>Not Supported: 35571/72706 (48.9%)</li><li>Warnings: 0/72706 (0.0%)</li>
</ul></details>

<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 34834/68473 (50.9%)</li>
<li>Failed: 0/68473 (0.0%)</li>
<li>Not Supported: 33639/68473 (49.1%)</li><li>Warnings: 0/68473 (0.0%)</li>
</ul></details>


</ul></details>

2022-09-28 07:38 UTC, jasilvanus commented on include/vkgcDefs.h
> +// Trace ray library manager interfaces, client needs to inherit and impelent it.
Typo: `impelent` -> `implement`

2022-09-28 08:06 UTC, nhaehnle requested changes
This sounds like a really useful development overall. However, this change in isolation is quite difficult to judge. It needs either an accompanying design document or the changes that build on top of it, and so I prefer we hold off on merging until these questions are settled properly.

I see the following major question areas:

1. Function call interface / ABI
2. Standalone compilation (amdllpc)
3. Interaction with multi-threaded compilation
4. Interaction with shader caching

## Function call interface / ABI

It is unclear to me whether the expected function signature of TraceRay depends on TraceRayParams, and whether the client is able to have a say in there.

For example, if the compiler requests a TraceRay implementation with `maxPayloadSize = 16`, is the driver allowed to provide an implementation with `maxPayloadSize = 32`?

How does the driver ultimately cause the correct version of TraceRay to be compiled? Do you plan to add another interface to the compiler where the driver can pass in the `TraceRayParams` as part of the compilation? It would seem useful to add this interface at the same time.

## Standalone compilation (amdllpc)

What's the plan here? First of all, for raytracing pipeline compilation I assume amdllpc will have a dummy implementation of `ITraceRayLibMgr` that just hands out sequential indices?

And how can a standalone compilation of TraceRay itself be triggered?

## Interaction with multi-threaded compilation

Since raytracing pipelines can be compiled in a multi-threaded fashion, so when can calls be made through `ITraceRayLibMgr`?

Can `GetTraceRayIndex` be called from a deferred operation or is it always called before the initial deferred operation return? To really make the most of multi-threaded compilation, it seems quite useful to be able to defer it. That implies that the implementation must be prepared to be called from multiple threads.

At the very least, the threading behavior of `ITraceRayLibMgr` needs to be documented. 

## Interaction with shader caching

Specifically, I'm thinking here about the case of a raygen shader which could be cached on disk. On a subsequent application run, are we guaranteed to get the same arrangement of the trace ray table? I don't expect so.

So what's the solution?

We could add the trace ray index to the cache hash, but it seems pretty lame to have to recompile just because that index changed. It also prevents us from ever moving the caching decision to an earlier point.

The alternative is to work with ELF relocations: let's say you're aiming to generate ISA that looks something like:
```
; s[20:21] points to the trace ray table
s_load_b64 s[16:17], s[20:21], (index * 8)
s_waitcnt lgkmcnt(0)
s_swappc_b64 s[30:31], s[16:17]   ; call TraceRay
```
Instead of hard-coding the `index` in the ELF file generated for raygen, we could instead have a relocation there:
```
; s[20:21] points to the trace ray table
s_load_b64 s[16:17], s[20:21], drt_traceray_index_qqqqqqqqqqqqqqqq@abs32@lo
s_waitcnt lgkmcnt(0)
s_swappc_b64 s[30:31], s[16:17]   ; call TraceRay
```
The `drt_traceray_index_qqqqqqqqqqqqqqqq` is a symbol name where the `qqqqqqqqqqqqqqqq` is replaced by the hex encoding of `TraceRayParams::u64all`.

We would still use some interface between the compiler and the driver to notify the driver about the require TraceRayParams, but we would no longer get an index back. Instead, the driver will coordinate with PAL to ensure that PAL's ELF loader can correctly resolve the relocation.

Once we're at this point conceptually, we can go one step further. If we're using relocations anyway, we don't even need the traceray table anymore and can instead generate the following code sequence:
```
s_getpc_b64 s[16:17]
s_mov_b32 s16, rt_traceray_qqqqqqqqqqqqqqqq@abs32@lo
s_swappc_b64 s[30:31], s[16:17]   ; call TraceRay
```
Here, the symbol `rt_traceray_qqqqqqqqqqqqqqqq` refers to the address of the actual function compiled TraceRay function.

This allows shaders to be cached without any problems and even has the benefit of being slightly more performant on the GPU.

2022-09-28 09:35 UTC, LLJJDD commented
Thanks for this very detailed comment! Let me answer:

> For example, if the compiler requests a TraceRay implementation with `maxPayloadSize = 16`, is the driver allowed to provide an implementation with `maxPayloadSize = 32`?

Client is expected to provide an implementation which all TraceRayParams are matched exactly. If we can prove that some combinations are compatible in the future, we may loosen that restriction.

> How does the driver ultimately cause the correct version of TraceRay to be compiled? Do you plan to add another interface to the compiler where the driver can pass in the `TraceRayParams` as part of the compilation? It would seem useful to add this interface at the same time.

Yes, driver needs to tell compiler what parameters are used.

I've already opened an internal PR of implementation on driver side earlier, you may take a look at that about how driver would interact with compiler.

> 
> ## Standalone compilation (amdllpc)
> What's the plan here? First of all, for raytracing pipeline compilation I assume amdllpc will have a dummy implementation of `ITraceRayLibMgr` that just hands out sequential indices?
> 
> And how can a standalone compilation of TraceRay itself be triggered?

I haven't actually thought much about this :(

But basically there will be a new interface added to build a TraceRay library (Tentatively `Compiler::BuildSpecializedTraceRayLibrary`, like `Compiler::BuildRayTracingPipeline`), it should be easy for amdllpc to make use of it.

> ## Interaction with multi-threaded compilation

Currently my thought is that the client implementation uses a mutex to ensure only one thread is acquiring/compiling a TraceRay, to ensure we are not messing up the index or compiling a same version of TraceRay. In that way, `GetTraceRayIndex` could be called at any time.

> ## Interaction with shader caching
> Specifically, I'm thinking here about the case of a raygen shader which could be cached on disk. On a subsequent application run, are we guaranteed to get the same arrangement of the trace ray table? I don't expect so.
> 
> So what's the solution?

Good point, unfortunately this is something I was unaware of. Relocations looks good, but I'm not familiar with it. I believe I need to take a closer look on this.

I would like to propose a short-term and simpler way: maybe we can also get the `index` from cache, and just rebuild the trace ray table with `TraceRayParams` on the correct `index`, leaving unused index blank.

Hope the above explains some of your questions!

2022-09-28 10:17 UTC, LLJJDD commented on include/vkgcDefs.h
> +    uint64_t rayFlags : 32;         ///< Constant ray flags value, 0xFFFFFFFF for non-constant.
Good point! Not sure whether it is feasible for front-end to track down every known bit, but I'll take a look. Thanks!

2022-09-29 09:31 UTC, nhaehnle commented
Thank you for the detailed reply.

> But basically there will be a new interface added to build a TraceRay library (Tentatively `Compiler::BuildSpecializedTraceRayLibrary`, like `Compiler::BuildRayTracingPipeline`), it should be easy for amdllpc to make use of it.

Yes, makes sense. It could just be BuildTraceRayLibrary or perhaps a mode of BuildRayTracingPipeline. But yeah, amdllpc should be able to re-use this, we should just make sure that the necessary options are all there (e.g. .pipe dumping and loading).

> Currently my thought is that the client implementation uses a mutex to ensure only one thread is acquiring/compiling a TraceRay, to ensure we are not messing up the index or compiling a same version of TraceRay. In that way, GetTraceRayIndex could be called at any time.

Sounds good to me. Should be documented with a comment.

> I would like to propose a short-term and simpler way: maybe we can also get the index from cache, and just rebuild the trace ray table with TraceRayParams on the correct index, leaving unused index blank.

I'm not sure how that would work? What if the index is already occupied?

2022-09-29 14:49 UTC, LLJJDD commented
Let's just forget about this... As we've reached a consensus in our internal discussion to use relocations instead of indices, I'm closing this PR and will rework on the implementation.

2022-09-29 14:49 UTC, closed without merging