Revert the optimiaztion for the issue exposed by VK_EXT_image_sliced_…
GPUOpen-Drivers/llpc pull request #2322
Opened 2023-03-01 03:33 UTC by ruiminzhao

…view_of_3d

    This issue has been exposed by the new extension: VK_EXT_image_sliced_view_of_3d.There are some cases failed on LLPC:

    Taking the shader codes for example:

        layout (local_size_x=8, local_size_y=8, local_size_z=1) in;
        layout (rgba8ui, set=0, binding=0) uniform uimage3D slicedImage;
        layout (rgba8ui, set=0, binding=1) uniform uimage3D auxiliarImage;
        void main (void) {
            const ivec3 coords = ivec3(ivec2(gl_LocalInvocationID.xy), int(gl_WorkGroupID.x));
            const ivec3 size = imageSize(slicedImage);
            const uvec4 badColor = uvec4(0, 0, 0, 0);
            const uvec4 goodColor = imageLoad(slicedImage, coords);
            const uvec4 storedColor = ((size.z == 1) ? goodColor : badColor);
            imageStore(auxiliarImage, coords, storedColor);
        }
    With current optimization, LLPC will extract related bits from SRD in ImageBuilder::CreateImageQuerySize.  Two issues here:
        1.      The calculation logic for “depth”  is different between LLPC and driver side,
                especially for Dim3D, more variables are used under the driver side and the calculation logic is hard to replay on CreateImageQuerySize。
        2.      About mipLevel: for some failed cases on this extension, there isn’t any OpImageQueryLod in the shader, so even the image has some mipLevel info, it hasn’t been queried.
                Then “depth = CreateLShr(depth, CreateAdd(baseLevel, lod));” will be failed as lod is always zero.

2023-03-01 03:49 UTC, ruiminzhao commented
retest this please

2023-03-01 05:41 UTC, ruiminzhao commented
@ashleysmithamd There is a CI error seems imported with the commit:  901489852, please have a look.

901489852 lgc/builder/DescBuilder.cpp          (Ashley Smith        2023-02-21 11:01:03 +0000  96)         return PoisonValue::get(getBufferDescTy(pointeeTy));

Error info:
/vulkandriver/drivers/llpc/lgc/builder/DescBuilder.cpp: In member function ‘virtual llvm::Value* lgc::DescBuilder::CreateLoadBufferDesc(unsigned int, unsigned int, llvm::Value*, unsigned int, const llvm::Twine&)’:
/vulkandriver/drivers/llpc/lgc/builder/DescBuilder.cpp:96:49: error: ‘pointeeTy’ was not declared in this scope
   96 |         return PoisonValue::get(getBufferDescTy(pointeeTy));
      |                                                 ^~~~~~~~~

2023-03-01 05:42 UTC, ruiminzhao commented
@nhaehnle  Please have a review on this, more details can refer the E-mail. Thanks.

2023-03-01 10:21 UTC, Flakebi commented
> There is a CI error seems imported with the commit…

This is fixed in #2324.

These issues – conflicts between multiple PRs where CI passes on them, but not when combining them – are relatively seldom (every few months), but we could fix them by using merge queues. With merge queues, the CI runs on a commit merged (or rebased) into dev and that exact commit gets pushed if CI passes.

GitHub docs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

2023-03-01 12:03 UTC, nhaehnle commented
> @nhaehnle Please have a review on this, more details can refer the E-mail. Thanks.

Yes, will take a closer look.

2023-03-01 21:37 UTC, nhaehnle requested changes
Let's use https://github.com/GPUOpen-Drivers/llpc/pull/2325 instead assuming it works.

2023-03-02 03:44 UTC, ruiminzhao commented
Close this PR as there will be a better solution on https://github.com/GPUOpen-Drivers/llpc/pull/2325

2023-03-02 03:44 UTC, closed without merging