Disable test for upstream change to mbcnt
GPUOpen-Drivers/llpc pull request #2569
Opened 2023-06-30 21:43 UTC by Sisyph

Upstream LLVM commit 5ccfc4543d1784ed98cfae52364e438de5a993a6 optimizes mbcnt_hi in wave32. Update the test, and do not run it to give some time for users with older LLVM to get the change.

2023-07-01 07:10 UTC, jayfoad approved these changes

2023-07-01 08:00 UTC, amdvlk-admin commented
### Test summary for commit f943e7f429733b060913707298afd87ce8fabfcf
<details><summary>CTS tests (Failed: 0/211351)</summary><ul><li>Built with version 1.3.3.1</li>
<details open><summary>Rhel 9.0, Gfx10</summary><ul>

<li>Passed: 35147/70456 (49.9%)</li>
<li>Failed: 0/70456 (0.0%)</li>
<li>Not Supported: 35309/70456 (50.1%)</li><li>Warnings: 0/70456 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi3x</summary><ul>

<li>Passed: 39024/70454 (55.4%)</li>
<li>Failed: 0/70454 (0.0%)</li>
<li>Not Supported: 31430/70454 (44.6%)</li><li>Warnings: 0/70454 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Navi2x</summary><ul>

<li>Passed: 39058/70441 (55.4%)</li>
<li>Failed: 0/70441 (0.0%)</li>
<li>Not Supported: 31383/70441 (44.6%)</li><li>Warnings: 0/70441 (0.0%)</li>
</ul></details>


</ul></details>

2023-07-05 09:57 UTC, nhaehnle approved these changes

2023-07-05 10:02 UTC, jayfoad requested changes
This is wave 64 code (it even says so in the file name!) so it seems wrong that LLVM has removed the mbcnt_hi. I think this is showing that LLPC runs InstCombine before it has correctly set the wave size function attributes.

2023-07-05 10:26 UTC, nhaehnle commented
Oohh.. well spotted. The `wavefrontsize` feature is currently set in PatchSetupTargetFeatures, which runs very late.

It's unfortunate that the work to properly isolate when we choose the wave size was never finished, so this is now a bit of a mess.

`mbcnt`s generally exist from when the BuilderReplayer runs at the top of the `lgc::Patch` pipeline, so the target feature has to be set at that time as well. The PatchSetupTargetFeatures pass can't just be moved as-is because it relies on calling conventions a bunch.

Perhaps what you can do is:

* Set the wave size target feature attribute in the BuilderReplayer, because at that time we de facto already decide the wave size today.
* Change the PatchSetupTargetFeatures pass to *append* additional target features to an existing attribute.

2024-01-16 04:47 UTC, closed without merging