Trivial fix for #944
GPUOpen-Drivers/llpc pull request #954
Opened 2020-09-08 08:22 UTC by LLJJDD

#944 is caused by a PHI node tries to replaceAllUsesWIth itself.

2020-09-08 10:26 UTC, nhaehnle commented
I know it's not your fault, but the code you're modifying is pretty bizarre, e.g. using hard-coded phi node incoming indices. Could you please explain what it does? The comment at the top of the `if (numIncomings == 3)` section is pretty mysterious and should be expanded.

2020-09-08 20:20 UTC, kuhar requested changes
This should probably un-xfail the test case for #944: `llpc/test/shaderdb/fuzzer/GraphicsFuzz_ReplaceAllUsesWithNotValid.spvasm`

2020-09-09 04:18 UTC, LLJJDD commented
> I know it's not your fault, but the code you're modifying is pretty bizarre, e.g. using hard-coded phi node incoming indices. Could you please explain what it does? The comment at the top of the `if (numIncomings == 3)` section is pretty mysterious and should be expanded.

From my understanding, the code is trying to find two pairs of identical phi nodes and collapse them into one. The procedure is like:

1. There is a `phiNode` `%phi1 = phi [%a], [%b], [%b]`, its second and third incoming value are the same (`%b`), go on and take `%b` as `subPhiNode`.
2. Examine all of the `subPhiNode` `%b` is either `%phi1` or constant (`%b = phi [%phi1] [constant]`), if so, go on .
3. Take the phi user of `phiNode.getIncomingValue(0) (%a)` , as `otherPhiNode`, for example, `%phi2 = [%a], [%c], [%c]`, `%phi2` has to be in the same parent block as `%phi1`
4. If the `otherPhiNode` also has 3 incoming values, and the second and third are the same (`%c`), take it as `otherSubPhiNode`.
5. Then check whether `%c` is identical to `%b` by examing their incoming value and block, `%c` and `%b` have to be in the same parent block.
6. If `%c` is proven to be identical to `%b`, then `%phi1` is identical to `%phi2`, so replace `%phi2` with `%phi1`, `%c` with `%b`.

2020-09-09 08:30 UTC, amdvlk-admin commented
### Test summary for commit 03517d5d57f8c8a974036a488e6982a7beaff1d8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c72fe645f96434578da68c6fdb44bd28bb2fa6f1</li>
</ul></details>

<details><summary>CTS tests (Failed: 3/131664)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43895 (51.9%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 21111/43895 (48.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22780/43895 (51.9%)</li>
<li><details><summary>Failed: 3/43895 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.draw.instanced.draw_indexed_indirect_vk_primitive_topology_triangle_fan_attrib_divisor_1
Stack trace: Flake

FAILURE: dEQP-VK.memory.pipeline_barrier.host_write_storage_texel_buffer.8192
Stack trace: Flake

FAILURE: dEQP-VK.renderpass2.dedicated_allocation.formats.r32_sfloat.clear.draw
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21112/43895 (48.1%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43874 (49.3%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 22265/43874 (50.7%)</li>
</ul></details>


</ul></details>

2020-09-09 08:37 UTC, dstutt commented
Latest LLVM (I'm currently mid-way through manually fixing the latest auto-merge) also fixes this issue.
If we can get this change in (and the test passing), then it'll mean I can push the latest LLVM through, otherwise we should remove the test (although I suspect this issue is still a problem).

2020-09-09 08:43 UTC, dstutt commented
retest this please

2020-09-09 08:45 UTC, amdrexu commented
If LLVM promotion could fix this issue, it's fine. We can drop this change in front-end. The context of peephole optimization is unclear to us. It is difficult for us to refactor this file in short run.

2020-09-09 08:48 UTC, dstutt commented
Ok - in that case we should remove the test for now. There's a race condition that means I can't push the auto-merge through until this test succeeds (which it won't), but I can't mark it as passing as that will fail in GitHub until the promotion happens.

I'll submit another PR to remove the test (and explain why).

2020-09-09 08:53 UTC, nhaehnle commented
> > I know it's not your fault, but the code you're modifying is pretty bizarre, e.g. using hard-coded phi node incoming indices. Could you please explain what it does? The comment at the top of the `if (numIncomings == 3)` section is pretty mysterious and should be expanded.
> 
> From my understanding, the code is trying to find two pairs of identical phi nodes and collapse them into one. The procedure is like:
> 
>     1. There is a `phiNode` `%phi1 = phi [%a], [%b], [%b]`, its second and third incoming value are the same (`%b`), go on and take `%b` as `subPhiNode`.
> 
>     2. Examine all of the `subPhiNode` `%b` is either `%phi1` or constant (`%b = phi [%phi1] [constant]`), if so, go on .
> 
>     3. Take the phi user of `phiNode.getIncomingValue(0) (%a)` , as `otherPhiNode`, for example, `%phi2 = [%a], [%c], [%c]`, `%phi2` has to be in the same parent block as `%phi1`
> 
>     4. If the `otherPhiNode` also has 3 incoming values, and the second and third are the same (`%c`), take it as `otherSubPhiNode`.
> 
>     5. Then check whether `%c` is identical to `%b` by examing their incoming value and block, `%c` and `%b` have to be in the same parent block.
> 
>     6. If `%c` is proven to be identical to `%b`, then `%phi1` is identical to `%phi2`, so replace `%phi2` with `%phi1`, `%c` with `%b`.

Thank you for the explanations. I've been looking into this further, and there are some additional discrepancies in the code:

1. `subPhiNodeOptimizable` can be set to false while analyzing a user and will not be reset when analyzing the next user.
2. The check `otherIncoming != otherPhiNode && otherIncoming != incoming` for equivalence of the "sub phis" looks incorrect to me. What it should check for is that either both sub phis refer to the same constant, or both refer to phiNode or otherPhiNode. As-is, the check will incorrectly accept the case where subPhiNode has an incoming constant and otherSubPhiNode has otherPhiNode as incoming for the same predecessor.

At a higher level, though, the whole thing is too special-cased and should probable be removed. Please see issue #957.

Overall, I think this change does fix a bug, but you should fix all the bugs as long as we're looking at this code, and perhaps we can just get rid of the code entirely.

2020-09-09 09:10 UTC, amdvlk-admin commented
### Test summary for commit 03517d5d57f8c8a974036a488e6982a7beaff1d8
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 712f76fee75d69b23a1ea8f6465752c3ccaaf9a2</li>
<li>PAL: dev 9074bd0bdaf67fa84399dfabed3ec437951838f8</li>
<li>SPVGEN: dev c054813a9a894e32aaaa04c6717a667c15f60cfd</li>
<li>XGL: dev 598c6832a4983f5b75b38a589fca5be80a2f3bb0</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev c72fe645f96434578da68c6fdb44bd28bb2fa6f1</li>
</ul></details>

<details><summary>CTS tests (Failed: 1/131664)</summary><ul><li>Built with branch Vulkan-CTS-1.2.0.2-fetch-sources-fix</li>
<details open><summary>Ubuntu 20.04, Gfx10</summary><ul>

<li>Passed: 22784/43895 (51.9%)</li>
<li>Failed: 0/43895 (0.0%)</li>
<li>Skipped: 21111/43895 (48.1%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 22782/43895 (51.9%)</li>
<li><details><summary>Failed: 1/43895 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.timeline_semaphore.one_to_n.write_image_compute_indirect_read_image_compute.image_128x128_r8_unorm
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 21112/43895 (48.1%)</li>
</ul></details>

<details open><summary>Rhel 8.2, Gfx8</summary><ul>

<li>Passed: 21609/43874 (49.3%)</li>
<li>Failed: 0/43874 (0.0%)</li>
<li>Skipped: 22265/43874 (50.7%)</li>
</ul></details>


</ul></details>

2020-09-11 04:18 UTC, JaxLinAMD commented
@LLJJDD please resolve conflicts

2020-09-11 09:48 UTC, dstutt commented
If the conflicts are resolved, lets go with this change. I'll look at progressing Issue #957 rather than attempting to fix any of the other issues highlighted (biggest problem is the test cases).

2020-09-14 02:14 UTC, LLJJDD commented
Conflict resolved.

2020-09-14 05:50 UTC, JaxLinAMD commented
retest this please

2020-09-14 08:12 UTC, JaxLinAMD commented
please rebase to latest dev and push again to make jenkins build pass

2020-09-18 02:04 UTC, LLJJDD commented
I'm closing this PR since #969 is removing this part of code and also fixing #944

2020-09-18 02:04 UTC, closed without merging